<?php
// 如果直接访问此文件，请中止。
defined('ABSPATH') || exit;
/**
 * 模块注册表
 *
 * 定义所有功能模块的元数据，替代硬编码的 build_active_modules_map + activate_module。
 *
 * @since 2.1.0
 */

return array(

    // ========== 站点优化 ==========
    'optimize.hide_top_toolbar' => array(
        'class'       => 'Npcink_Toolbox_Hide_Top_Toolbar',
        'file'        => 'optimize/site/hide_top_toolbar.php',
        'option_key'  => 'optimize.site.hide_top_toolbar',
        'category'    => 'optimize',
        'scope'       => 'both',
        'risk_tags'   => array('推荐', '仅后台'),
        'label'       => '隐藏顶部工具条',
        'group'       => '站点',
        'feature_id'  => 'optimize-site-hide_top_toolbar',
        'risk'        => array('level' => 'none'),
        'depends_on'  => array(),
        'preset_tags' => array('pure', 'blog'),
    ),
    'optimize.no_escape' => array(
        'class'       => 'Npcink_Toolbox_No_Escape',
        'file'        => 'optimize/site/no_escape.php',
        'option_key'  => 'optimize.site.no_escape',
        'category'    => 'optimize',
        'scope'       => 'frontend',
        'risk_tags'   => array('推荐'),
        'label'       => '禁止 Title 转义',
        'group'       => '站点',
        'feature_id'  => 'optimize-site-no_escape',
        'risk'        => array('level' => 'none'),
        'depends_on'  => array(),
        'preset_tags' => array('pure', 'blog'),
    ),
    'optimize.remove_wp_version' => array(
        'class'     => 'Npcink_Toolbox_Remove_WP_Version',
        'label'     => '移除版本信息',
        'file'      => 'optimize/site/remove_wp_version.php',
        'option_key'=> 'optimize.site.remove_RSS_version',
        'category'  => 'optimize',
        'scope'     => 'both',
        'risk_tags' => array('推荐', '安全'),
    ),
    'optimize.category_link_simplify' => array(
        'class'     => 'Npcink_Toolbox_Category_Link_Simplify',
        'label'     => '分类链接简化',
        'file'      => 'optimize/site/category_link_simplify.php',
        'option_key'=> 'optimize.site.category_link_simplify',
        'category'  => 'optimize',
        'scope'     => 'both',
        'risk_tags' => array('SEO'),
    ),
    'optimize.search_link_simplify' => array(
        'class'     => 'Npcink_Toolbox_Search_Link_Simplify',
        'label'     => '搜索链接优化',
        'file'      => 'optimize/site/search_link_simplify.php',
        'option_key'=> 'optimize.site.search_link_simplify',
        'category'  => 'optimize',
        'scope'     => 'frontend',
        'risk_tags' => array('SEO'),
    ),
    'optimize.remove_sitemap_users' => array(
        'class'     => 'Npcink_Toolbox_Remove_Sitemap_Users',
        'label'     => '移除用户站点地图',
        'file'      => 'optimize/site/remove_sitemap_users.php',
        'option_key'=> 'optimize.site.remove_sitemap_users',
        'category'  => 'optimize',
        'scope'     => 'frontend',
        'risk_tags' => array('推荐', '安全'),
    ),
    'optimize.user_list_show_nickname' => array(
        'class'     => 'Npcink_Toolbox_User_List_Show_Nickname',
        'label'     => '用户列表展示昵称',
        'file'      => 'optimize/site/user_list_show_nickname.php',
        'option_key'=> 'optimize.site.user_list_show_nickname',
        'category'  => 'optimize',
        'scope'     => 'admin',
        'risk_tags' => array('仅后台'),
    ),
    'optimize.hide_email_ip' => array(
        'class'     => 'Npcink_Toolbox_Hide_Email_IP',
        'label'     => '隐藏邮件中的 IP',
        'file'      => 'optimize/site/hide_email_ip.php',
        'option_key'=> 'optimize.site.hide_email_ip',
        'category'  => 'optimize',
        'scope'     => 'both',
        'risk_tags' => array('推荐', '安全'),
    ),
    'optimize.widgets' => array(
        'class'     => 'Npcink_Toolbox_Widgets',
        'label'     => '站点小工具',
        'file'      => 'optimize/widget/index.php',
        'option_key'=> 'optimize.widgets',
        'category'  => 'optimize',
        'scope'     => 'both',
        'always_load' => true,
        'risk_tags' => array('推荐'),
    ),
    'optimize.image_add_tag' => array(
        'class'     => 'Npcink_Toolbox_Image_Add_Tag',
        'label'     => '图片自动添加 Alt 标签',
        'file'      => 'optimize/medium/image_add_tag.php',
        'option_key'=> 'optimize.medium.img_add_tag',
        'category'  => 'optimize',
        'scope'     => 'frontend',
        'risk_tags' => array('推荐', 'SEO'),
    ),
    'optimize.ban_auto_size' => array(
        'class'     => 'Npcink_Toolbox_Medium_Ban_Auto_Size',
        'file'      => 'optimize/medium/ban_auto_size.php',
        'option_key'=> 'optimize.medium.no_auto_size',
        'category'  => 'optimize',
        'scope'     => 'both',
        'label'     => '禁止缩略图',
        'risk_tags' => array('谨慎', '需主题兼容'),
    ),
    'optimize.svg_support' => array(
        'class'     => 'Npcink_Toolbox_Medium_Svg_Support',
        'label'     => '添加 SVG 图标支持',
        'file'      => 'optimize/medium/svg_support.php',
        'option_key'=> 'optimize.medium.medium_add_svg',
        'category'  => 'optimize',
        'scope'     => 'both',
        'risk_tags' => array('进阶', 'XSS 风险'),
    ),
    'optimize.image_rename' => array(
        'class'     => 'Npcink_Toolbox_Medium_Image_Rename',
        'label'     => '上传文件重命名',
        'file'      => 'optimize/medium/image_rename.php',
        'option_key'=> 'optimize.medium.upload_auto_name',
        'category'  => 'optimize',
        'scope'     => 'both',
        'config_path' => 'optimize.medium',
        'risk_tags' => array('推荐'),
    ),
    'optimize.webp_conversion' => array(
        'class'       => 'Npcink_Toolbox_Medium_Webp_Conversion',
        'file'        => 'optimize/medium/webp_conversion.php',
        'option_key'  => 'optimize.medium.webp_conversion',
        'category'    => 'optimize',
        'scope'       => 'both',
        'config_path' => 'optimize.medium',
        'label'       => '新生成图片使用 WebP',
        'group'       => '媒体',
        'feature_id'  => 'optimize-medium-webp_conversion',
        'risk_tags'   => array('性能', '安全'),
        'risk'        => array('level' => 'none'),
        'depends_on'  => array(),
        'preset_tags' => array('performance'),
    ),
    'optimize.admin_single_add_user_screen' => array(
        'class'     => 'Npcink_Toolbox_Admin_Single_Add_User_Screen',
        'label'     => '添加作者筛选项',
        'file'      => 'optimize/admin/single_add_user_screen.php',
        'option_key'=> 'optimize.admin.add_user',
        'category'  => 'optimize',
        'scope'     => 'admin',
        'risk_tags' => array('仅后台'),
    ),
    'optimize.admin_add_time_screen' => array(
        'class'     => 'Npcink_Toolbox_Admin_Add_Time_Screen',
        'label'     => '添加时间筛选项',
        'file'      => 'optimize/admin/add_time_screen.php',
        'option_key'=> 'optimize.admin.add_time',
        'category'  => 'optimize',
        'scope'     => 'admin',
        'risk_tags' => array('仅后台'),
    ),
    'optimize.admin_single_show_id' => array(
        'class'     => 'Npcink_Toolbox_Admin_Single_Show_ID',
        'label'     => '各个列表显示链接 ID',
        'file'      => 'optimize/admin/single_show_id.php',
        'option_key'=> 'optimize.admin.show_id',
        'category'  => 'optimize',
        'scope'     => 'admin',
        'risk_tags' => array('仅后台'),
    ),
    'optimize.admin_thumbnail_switcher' => array(
        'class'     => 'Npcink_Toolbox_Admin_Single_Thumbnail_Switcher',
        'label'     => '缩略图切换',
        'file'      => 'optimize/admin/thumbnail_switcher/index.php',
        'option_key'=> 'optimize.admin.thumbnail_switcher',
        'category'  => 'optimize',
        'scope'     => 'admin',
        'risk_tags' => array('仅后台'),
    ),

    // ========== 页面外观 ==========

    'page.reading_progress' => array(
        'class'     => 'Npcink_Toolbox_Page_Reading_Progress',
        'label'     => '阅读进度条',
        'file'      => 'page/exterior/reading_progress/index.php',
        'option_key'=> 'page.feature.reading_progress',
        'category'  => 'page',
        'scope'     => 'frontend',
        'config_path' => 'page.feature',
        'risk_tags' => array('仅前台'),
    ),
    // ========== 页面评论 ==========
    'page.comment_interval' => array(
        'class'     => 'Npcink_Toolbox_Page_Comment_Interval',
        'label'     => '两次评论间隔时间',
        'file'      => 'page/comment/comment_interval.php',
        'option_key'=> 'page.comment.interval',
        'category'  => 'page',
        'scope'     => 'frontend',
        'config_path' => 'page.comment',
    ),
    'page.limit_word_count' => array(
        'class'     => 'Npcink_Toolbox_Comment_Limit_Word_Count',
        'label'     => '限制评论字数',
        'file'      => 'page/comment/limit_word_count.php',
        'option_key'=> 'page.comment.words_number',
        'category'  => 'page',
        'scope'     => 'frontend',
        'config_path' => 'page.comment',
    ),
    'page.ban_pure_english' => array(
        'class'     => 'Npcink_Toolbox_Comment_Ban_Pure_English',
        'label'     => '禁止纯英文评论',
        'file'      => 'page/comment/ban_pure_english.php',
        'option_key'=> 'page.comment.english',
        'category'  => 'page',
        'scope'     => 'frontend',
        'config_path' => 'page.comment',
    ),
    'page.only_comment_once' => array(
        'class'     => 'Npcink_Toolbox_Comment_Only_Once',
        'label'     => '单篇文章仅限评论一次',
        'file'      => 'page/comment/only_comment_once.php',
        'option_key'=> 'page.comment.only',
        'category'  => 'page',
        'scope'     => 'frontend',
    ),
    'page.comment_sensitive_words' => array(
        'class'     => 'Npcink_Toolbox_Comment_Sensitive_Words',
        'label'     => '敏感词过滤',
        'file'      => 'page/comment/sensitive_words.php',
        'option_key'=> 'page.comment.sensitive_words',
        'category'  => 'page',
        'scope'     => 'frontend',
        'config_path' => 'page.comment',
    ),
    'page.my_comments' => array(
        'class'       => 'Npcink_Toolbox_My_Comments',
        'label'       => '用户评论自助管理',
        'file'        => 'page/comment/my_comments.php',
        'option_key'  => 'page.comment.self_service_enabled',
        'category'    => 'page',
        'scope'       => 'admin',
        'config_path' => 'page.comment',
        'risk_tags'   => array('需认证', 'REST API'),
    ),
    // ========== 页面功能 ==========
    'page.first_picture' => array(
        'class'     => 'Npcink_Toolbox_Single_First_Picture',
        'label'     => '首图作特色图',
        'file'      => 'page/function/first_picture.php',
        'option_key'=> 'page.function.first_picture',
        'category'  => 'page',
        'scope'     => 'frontend',
    ),
    'page.single_keyword_add_link' => array(
        'class'     => 'Npcink_Toolbox_Single_Keyword_Add_Link',
        'file'      => 'page/function/single_keyword_add_link.php',
        'option_key'=> 'page.function.add_inks',
        'category'  => 'page',
        'scope'     => 'frontend',
        'label'     => '关键词自动内链',
    ),
    'page.add_article_update_time' => array(
        'class'     => 'Npcink_Toolbox_Single_Add_Last_Updated_Date',
        'label'     => '添加最后更新时间',
        'file'      => 'page/function/add_article_update_time.php',
        'option_key'=> 'page.function.add_last_update',
        'category'  => 'page',
        'scope'     => 'frontend',
    ),
    'page.unlisted_vague_img' => array(
        'class'     => 'Npcink_Toolbox_Unlisted_Vague_Img',
        'label'     => '未登录模糊文章内图片',
        'file'      => 'page/function/unlisted_vague_img.php',
        'option_key'=> 'page.function.no_login_img',
        'category'  => 'page',
        'scope'     => 'frontend',
    ),
    'page.maintenance_tips' => array(
        'class'     => 'Npcink_Toolbox_Maintenance_Tips',
        'label'     => '维护提示页',
        'file'      => 'page/function/maintenance_tips.php',
        'option_key'=> 'page.function.maintenance_tips',
        'category'  => 'page',
        'scope'     => 'frontend',
        'config_path' => 'page.function',
    ),
    'page.default_thumbnail' => array(
        'class'     => 'Npcink_Toolbox_Page_Default_Thumbnail',
        'label'     => '默认缩略图',
        'file'      => 'page/function/default_thumbnail.php',
        'option_key'=> 'page.function.default_thumbnail',
        'category'  => 'page',
        'scope'     => 'frontend',
        'config_path' => 'page.function',
    ),
    'page.search_limit' => array(
        'class'     => 'Npcink_Toolbox_Page_Search_Limit',
        'label'     => '搜索频率限制',
        'file'      => 'page/function/search_limit.php',
        'option_key'=> 'page.function.search_limit',
        'category'  => 'page',
        'scope'     => 'frontend',
        'config_path' => 'page.function',
    ),
    'page.login_search' => array(
        'class'     => 'Npcink_Toolbox_Page_Login_Search',
        'label'     => '仅登录用户可搜索',
        'file'      => 'page/function/login_search.php',
        'option_key'=> 'page.function.login_search',
        'category'  => 'page',
        'scope'     => 'frontend',
    ),

    // ========== 页面权限 ==========
    'page.hide_category' => array(
        'class'     => 'Npcink_Toolbox_Page_Hide_Category',
        'file'      => 'page/jurisdiction/hide_category.php',
        'option_key'=> 'page.jurisdiction.category_id',
        'category'  => 'page',
        'scope'     => 'frontend',
        'config_path' => 'page.jurisdiction',
        'label'     => '隐藏指定分类文章',
        'risk_tags' => array('仅前台'),
    ),
    'page.hide_tag' => array(
        'class'     => 'Npcink_Toolbox_Page_Hide_Tag',
        'file'      => 'page/jurisdiction/hide_tag.php',
        'option_key'=> 'page.jurisdiction.tag_id',
        'category'  => 'page',
        'scope'     => 'frontend',
        'config_path' => 'page.jurisdiction',
        'label'     => '隐藏指定标签文章',
        'risk_tags' => array('仅前台'),
    ),
    'page.hide_page' => array(
        'class'     => 'Npcink_Toolbox_Page_Hide_Page',
        'file'      => 'page/jurisdiction/hide_page.php',
        'option_key'=> 'page.jurisdiction.page_id',
        'category'  => 'page',
        'scope'     => 'frontend',
        'config_path' => 'page.jurisdiction',
        'label'     => '隐藏指定页面',
        'risk_tags' => array('仅前台'),
    ),

    // ========== SEO ==========
    'seo.seo_home' => array(
        'class'     => 'Npcink_Toolbox_Seo_Home',
        'label'     => '首页 SEO',
        'file'      => 'function/seo/seo_home.php',
        'option_key'=> 'function.seo.seo_home',
        'category'  => 'function',
        'scope'     => 'frontend',
        'config_path' => 'function.seo',
        'risk_tags' => array('推荐', 'SEO'),
    ),
    'seo.seo_single' => array(
        'class'     => 'Npcink_Toolbox_Seo_Single',
        'label'     => '文章 SEO',
        'file'      => 'function/seo/seo_single.php',
        'option_key'=> 'function.seo.seo_single',
        'category'  => 'function',
        'scope'     => 'frontend',
        'risk_tags' => array('推荐', 'SEO'),
    ),
    'seo.seo_category_add_meat' => array(
        'class'     => 'Npcink_Toolbox_Seo_Category_Add_Meat',
        'label'     => '分类 SEO 字段',
        'file'      => 'function/seo/seo_category_add_meat.php',
        'option_key'=> 'function.seo.seo_category',
        'category'  => 'function',
        'scope'     => 'admin',
        'risk_tags' => array('SEO'),
    ),
    'seo.seo_category' => array(
        'class'     => 'Npcink_Toolbox_Seo_Category',
        'label'     => '分类 SEO',
        'file'      => 'function/seo/seo_category.php',
        'option_key'=> 'function.seo.seo_category',
        'category'  => 'function',
        'scope'     => 'frontend',
        'risk_tags' => array('SEO'),
    ),
    'seo.seo_tag' => array(
        'class'     => 'Npcink_Toolbox_Seo_Tag',
        'label'     => '标签 SEO',
        'file'      => 'function/seo/seo_tag.php',
        'option_key'=> 'function.seo.seo_category',
        'category'  => 'function',
        'scope'     => 'frontend',
        'risk_tags' => array('SEO'),
    ),

    // ========== 辅助功能 ==========
    'auxiliary.census_single' => array(
        'class'     => 'Npcink_Toolbox_Census_Single',
        'label'     => '文章访问统计',
        'file'      => 'function/auxiliary/census-single.php',
        'option_key'=> 'function.auxiliary.single_count',
        'category'  => 'function',
        'scope'     => 'both',
    ),
    'auxiliary.ban_malice_search' => array(
        'class'     => 'Npcink_Toolbox_Ban_Malice_Search',
        'label'     => '屏蔽恶意关键词搜索',
        'file'      => 'function/auxiliary/ban_malice_search.php',
        'option_key'=> 'function.auxiliary.no_malice_key',
        'category'  => 'function',
        'scope'     => 'frontend',
        'config_path' => 'function.auxiliary',
    ),
    'auxiliary.baidu_tonji' => array(
        'class'     => 'Npcink_Toolbox_Baidu_Tonji',
        'file'      => 'function/auxiliary/baidu_tonji.php',
        'option_key'=> 'function.auxiliary.baidu_tonji',
        'category'  => 'function',
        'scope'     => 'frontend',
        'config_path' => 'function.auxiliary',
        'label'     => '百度统计',
    ),
    'auxiliary.google_tonji' => array(
        'class'     => 'Npcink_Toolbox_Google_Tonji',
        'file'      => 'function/auxiliary/google_tonji.php',
        'option_key'=> 'function.auxiliary.google_tonji',
        'category'  => 'function',
        'scope'     => 'frontend',
        'config_path' => 'function.auxiliary',
        'label'     => 'Google Analytics',
    ),
    'auxiliary.biying_tonji' => array(
        'class'     => 'Npcink_Toolbox_Biying_Tonji',
        'file'      => 'function/auxiliary/biying_tonji.php',
        'option_key'=> 'function.auxiliary.biying_tonji',
        'category'  => 'function',
        'scope'     => 'frontend',
        'config_path' => 'function.auxiliary',
        'label'     => '必应统计',
    ),

    // ========== 页面 jurisdiction interface ==========
    'page.interface_category_data' => array(
        'class'     => 'Npcink_Toolbox_Interface_Category_Data',
        'label'     => '分类数据接口',
        'file'      => 'page/jurisdiction/interface_category_data.php',
        'option_key'=> 'page.jurisdiction.category_id',
        'category'  => 'page',
        'scope'     => 'admin',
    ),

    // ========== 国内生态 - 备案与合规 ==========
    'domestic.compliance' => array(
        'class'            => 'Npcink_Toolbox_Domestic_Compliance',
        'label'            => '备案与合规',
        'file'             => 'domestic/compliance/index.php',
        'option_key'       => 'domestic.compliance.icp_enabled',
        'activation_paths' => array(
            'domestic.compliance.icp_enabled',
            'domestic.compliance.police_enabled',
            'domestic.compliance.cookie_enabled',
            'domestic.compliance.copyright_enabled',
        ),
        'category'         => 'domestic',
        'scope'            => 'frontend',
        'config_path'      => 'domestic.compliance',
        'risk_tags'        => array('推荐'),
    ),

    // ========== 国内生态 - 微信生态 ==========
    'domestic.wechat' => array(
        'class'            => 'Npcink_Toolbox_Domestic_Wechat',
        'label'            => '微信生态',
        'file'             => 'domestic/wechat/index.php',
        'option_key'       => 'domestic.wechat.jssdk_enabled',
        'activation_paths' => array(
            'domestic.wechat.jssdk_enabled',
            'domestic.wechat.guide_overlay_enabled',
        ),
        'category'         => 'domestic',
        'scope'            => 'frontend',
        'config_path'      => 'domestic.wechat',
        'risk_tags'        => array('推荐'),
    ),

    // ========== 国内生态 - 评论安全 ==========
    'domestic.comment_security' => array(
        'class'            => 'Npcink_Toolbox_Domestic_Comment_Security',
        'label'            => '评论安全',
        'file'             => 'domestic/comment_security/index.php',
        'option_key'       => 'domestic.comment_security.blacklist_enabled',
        'activation_paths' => array(
            'domestic.comment_security.blacklist_enabled',
            'domestic.comment_security.link_limit_enabled',
            'domestic.comment_security.nickname_filter_enabled',
            'domestic.comment_security.email_domain_enabled',
            'domestic.comment_security.duplicate_enabled',
            'domestic.comment_security.ip_rate_enabled',
            'domestic.comment_security.log_enabled',
        ),
        'category'         => 'domestic',
        'scope'            => 'frontend',
        'config_path'      => 'domestic.comment_security',
        'risk_tags'        => array('推荐', '安全'),
    ),

    // ========== 国内生态 - 登录安全 ==========
    'domestic.login_security' => array(
        'class'            => 'Npcink_Toolbox_Domestic_Login_Security',
        'file'             => 'domestic/login_security/index.php',
        'option_key'       => 'domestic.login_security.attempt_limit_enabled',
        'activation_paths' => array(
            'domestic.login_security.attempt_limit_enabled',
            'domestic.login_security.anonymous_author_guard_enabled',
        ),
        'category'         => 'domestic',
        'scope'            => 'both',
        'config_path'      => 'domestic.login_security',
        'risk_tags'        => array('推荐', '安全'),
        'label'            => '登录安全',
        'group'            => '登录安全',
        'feature_id'       => 'domestic-login_security',
        'depends_on'       => array(),
        'preset_tags'      => array('security'),
    ),

    // ========== 性能优化 - 对象存储 ==========
    'performance.oss' => array(
        'class'     => 'Npcink_Toolbox_Performance_Oss',
        'label'     => '对象存储 / OSS',
        'file'      => 'performance/oss/index.php',
        'option_key'=> 'performance.oss.enabled',
        'category'  => 'performance',
        'scope'     => 'both',
        'config_path' => 'performance.oss',
        'risk_tags' => array('性能'),
    ),

    // ========== 性能优化 - SEO检查 ==========
    'performance.seo_checker' => array(
        'class'     => 'Npcink_Toolbox_Performance_Seo_Checker',
        'label'     => 'SEO 检查助手',
        'file'      => 'performance/seo_checker/index.php',
        'option_key'=> 'performance.seo_checker.enabled',
        'category'  => 'performance',
        'scope'     => 'admin',
        'config_path' => 'performance.seo_checker',
        'risk_tags' => array('SEO'),
    ),

    // ========== 性能优化 - 媒体库体检 ==========
    'performance.media_health' => array(
        'class'     => 'Npcink_Toolbox_Performance_Media_Health',
        'label'     => '媒体库体检',
        'file'      => 'performance/media_health/index.php',
        'option_key'=> 'performance.media_health.enabled',
        'category'  => 'performance',
        'scope'     => 'admin',
        'config_path' => 'performance.media_health',
        'risk_tags' => array('推荐'),
    ),

    // ========== 性能优化 - 搜索增强 ==========
    'performance.search_enhance' => array(
        'class'            => 'Npcink_Toolbox_Performance_Search_Enhance',
        'label'            => '搜索增强',
        'file'             => 'performance/search_enhance/index.php',
        'option_key'       => 'performance.search_enhance.highlight_enabled',
        'activation_paths' => array(
            'performance.search_enhance.highlight_enabled',
            'performance.search_enhance.recommend_enabled',
            'performance.search_enhance.hotwords_enabled',
        ),
        'category'         => 'performance',
        'scope'            => 'frontend',
        'config_path'      => 'performance.search_enhance',
        'risk_tags'        => array('推荐'),
    ),

    // ========== 性能优化 - 数据库清理 ==========
    'performance.db_clean' => array(
        'class'     => 'Npcink_Toolbox_Performance_Db_Clean',
        'file'      => 'performance/db_clean/index.php',
        'option_key'=> 'performance.db_clean.enabled',
        'category'  => 'performance',
        'scope'     => 'admin',
        'config_path' => 'performance.db_clean',
        'label'     => '数据库清理优化',
        'risk_tags' => array('高风险', '不可逆'),
    ),
);
